name: 'artefacts-ci'
description: 'Run Simulation Job using Artefacts'

inputs:
  artefacts-api-key:
    description: 'Artefacts API Key'
    required: true
  job-name:
    description: 'Name of the job to execute'
    required: true

runs:
  using: "composite"
  
  steps:
    - name: Ros 2 CI
    - uses: ros-tooling/setup-ros@v0.6
          with:
            required-ros-distributions: humble
        - uses: ros-tooling/action-ros-ci@v0.3
          with:
            import-token: ${{ secrets.GITHUB_TOKEN }}
            package-name: dolly_tests
            target-ros2-distro: humble
            skip-tests: true

    - name: Install artefacts client
      run: pip install artefacts-client --extra-index-url https://d5cw4z7oemmfd.cloudfront.net/pep503/
      shell: bash

    - name: Run remote job
      id: run-job
      run: |
        ARTEFACTS_KEY=${{ inputs.artefacts-api-key }} artefacts run-remote ${{ inputs.job-name }}
      shell: bash