name: "artefacts-ci"
description: "Run Simulation Job using Artefacts"

inputs:
  artefacts-api-key:
    description: "Artefacts API Key"
    required: true
  job-name:
    description: "Name of the job to execute"
    required: true
  config-file:
    description: "Name of the configuration file."
    default: "artefacts.yaml"
  description:
    description: "Additional information for the commit"
    required: false
  working-dir:
    description: "Working dir containing "
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Install artefacts client
      run: pip install artefacts-client --extra-index-url https://d5cw4z7oemmfd.cloudfront.net/pep503/
      shell: bash

    - name: Run remote job
      id: run-job
      run: |
        cd ${{inputs.working-dir}} && ARTEFACTS_KEY=${{ inputs.artefacts-api-key }} artefacts run-remote ${{ inputs.job-name }} --config ${{ inputs.config-file }} --description \"${{ inputs.description }}\"
      shell: bash
