name: "artefacts-ci"
description: "Run Simulation Job using Artefacts"

inputs:
  artefacts-api-key:
    description: "Artefacts API Key"
    required: true
  job-name:
    description: "Name of the job to execute"
    required: true
  config-file:
    description: "Name of the configuration file."
    default: "artefacts.yaml"
  description:
    description: "Additional information for the commit"
    required: false
    default: "Artefacts CI check"
  artefacts-api-url:
    description: "Artefacts API URL"
    required: false
    default: "https://app.artefacts.com/api"
  working-dir:
    description: "Working dir containing"
    required: false
    default: "."
  wait_for_results:
    description: "Wait for the job to check the job result before finishing the action. (Consumes more GH action time)"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Install artefacts client
      run: pip install artefacts-cli
      shell: bash

    - name: Set commit description
      id: set-description
      run: |
        # Check if there is a commit message
        if [ -n "${{ github.event.head_commit.message }}" ]; then
          # Extract the first line of the commit message
          description=$(echo "${{ github.event.head_commit.message }}" | sed -n '1p')
        else
          # Default description if no commit message is available (Or manual trigger)
          description="Artefacts CI check"
        fi
        # Output the description to the GitHub environment
        echo "DESCRIPTION=${description//[$'\t\r\n']/ }" >> $GITHUB_ENV
      shell: bash

    - name: Run remote job
      id: run-job
      run: |
        cd ${{ inputs.working-dir }} && ARTEFACTS_KEY=${{ inputs.artefacts-api-key }} ARTEFACTS_API_URL=${{ inputs.artefacts-api-url }} artefacts run-remote ${{ inputs.job-name }} --config ${{ inputs.config-file }} --description "$DESCRIPTION"
      shell: bash

    - name: Wait for platform to register the job
      run: sleep 60
      shell: bash

    - name: Extract project name from artefacts.yaml
      id: extract-project-name
      uses: mikefarah/yq@master
      with:
        cmd: project_name=$(yq e '.project' ${{ inputs.config-file }}) && echo "PROJECT_NAME=${project_name}" >> $GITHUB_ENV

    - name: Check job status
      if: ${{ inputs.wait_for_results == 'true' }}
      id: check-job
      run: |
        project_id=${{ env.PROJECT_NAME }}
        commit_id=${{ github.sha }}
        api_url="${{ inputs.artefacts-api-url }}/${project_id}/${commit_id}/job-status"
        job_status="in progress"
        while [ "$job_status" != "success" ] && [ "$job_status" != "failed" ]; do
          response=$(curl --silent --write-out "HTTPSTATUS:%{http_code}" "$api_url")
          body=$(echo $response | sed -e 's/HTTPSTATUS\:.*//g')
          status_code=$(echo $response | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
          if [ $status_code -eq 200 ]; then
            job_status=$(echo $body | awk -F'"' '/status/ {print $4}')
          else
            echo "Error: API request failed with status $status_code"
            exit 1
          fi
          if [ "$job_status" != "success" ] && [ "$job_status" != "failed" ]; then
            sleep 5  # Wait for 5 seconds before checking again
          fi
        done
        if [ "$job_status" == "success" ]; then
          echo "Job completed successfully."
        else
          echo "Job failed."
          exit 1
        fi
      shell: bash
