name: 'artefacts-ci'
description: 'Run Simulation Job using Artefacts'

inputs:
  artefacts_api_key:
    description: 'Artefacts API Key'
    required: true
  job_name:
    description: 'Name of the job to execute'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install artefacts client
      run: pip install artefacts-client --extra-index-url https://d5cw4z7oemmfd.cloudfront.net/pep503/
      shell: bash

    - name: Run remote job
      id: run-job
      run: |
        ARTEFACTS_KEY=${{ inputs.artefacts_api_key }} artefacts run-remote ${{ inputs.job_name }}
        if [ ${{ steps.run-job.exitcode }} -eq 0 ]; then
          echo "Simulation job succeeded"
        else
          echo "Simulation job failed"
          exit 1
        fi

      shell: bash