name: 'Test Action'
on: [push]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          artefacts_api_key: ${{ secrets.ARTEFACTS_API_KEY }}
          job_name: basic_tests