name: 'runsimjob'
description: 'Run Simulation Job using Artefacts'

inputs:
  artefacts_api_key:
    description: 'Artefacts API Key'
    required: true
    default: ${{ secrets.ARTEFACTS_API_KEY }}
  job_name:
    description: 'Name of the job to execute'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install artefacts client
      run: pip install artefacts-client --extra-index-url https://d5cw4z7oemmfd.cloudfront.net/pep503/

    - name: Run remote job
      id: run-job
      run: |
        artefacts run-remote command --api-key ${{ inputs.artefacts_api_key }} --job-name ${{ inputs.job_name }}

    - name: Set action result based on exit code
      id: set-action-result
      run: |
        if [ ${{ steps.run-job.exitcode }} -eq 0 ]; then
          echo "::set-output name=action-result::success"
        else
          echo "::set-output name=action-result::failure"

    - name: Check run remote status
      run: |
        if [ "${{ steps.set-action-result.outputs.action-result }}" == "success" ]; then
          exit 0
        else
          exit 1

      # This is important to set the exit status of the action
      shell: bash
